name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    #- name: github-action-publish-binaries
    #  uses: skx/github-action-publish-binaries@release-0.14
   # - name: Test
   #   run: dotnet test --no-restore --verbosity normal
    - shell: bash
      run: |
        mkdir Artifact
        mkdir Artifact/AutoPBW.WPF
        mkdir Artifact/AutoPBW.WPF/AutoPBW
        mv AutoPBW.WPF/bin/Release/net7.0-windows/* Artifact/AutoPBW.WPF/AutoPBW/
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: AutoPBW.WPF 
        path: Artifact/AutoPBW.WPF

